name: sonora
description: "Epic scrobbler & social media music integrator app"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^4.11.2
  macos_ui: ^2.1.10
  yaru: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false